### ISSUE TITLE
catalogCategory.create requires an invalid parameters

### ISSUE THREAD

**Issue by afreeland** [MadisonReed/magentoapi#11]
I was seeing issues when trying to create a category in Magento.  

Currently in **catalog_category.js**

```
 /**
    Create a new category and return its ID.
  */
  create: {
    mandatory: 'categoryId,data',
    optional: 'storeView'
  }
```

What [Magento API Supports](http://www.magentocommerce.com/api/soap/catalog/catalogCategory/catalog_category.create.html)

String: sessionId
Int: parentId
array: categoryData
string: storeView (optional)

After digging through the code and wondering why categoryId didnt translate to parentId...or data didnt translate to categoryData...I ended up just changing the create object to look like

```
create: {
    mandatory: 'parentId,categoryData',
    optional: 'storeView'
  }
```

This appears to of fixed my issued unless I was using it incorrectly.

**Comment by tmarshall** [comment]
@afreeland :+1:  would you like to open a PR?
