### ISSUE TITLE
not able to connect to server

### ISSUE THREAD

**Issue by sanjeevbelagali** [MadisonReed/magentoapi#47]
not able to connect to live server using
var magento = new MagentoAPI({
  host: config.host,
  port: 443,
  path: config.path,
  login: config.username,
  pass: config.pass,
  secure: true
});
using this code i am able co connect to localhost but not to host = "example.com"
i am getting following Error "Unknown XML-RPC tag \'TITLE\'', name: 'Error'

**Comment by Aniket10k** [comment]
I have same problem. Can anyone answer this issue?

**Comment by sanjeevbelagali** [comment]
@anu-kulkarni  if you have any authentication for apache server then this error occurs.
i solved this by adding in magento.js file 
var configDefaults = {
  host: mandatory,
  port: 443,
  path: mandatory,
  login: mandatory,
  pass: mandatory,
  parallelLimit: Infinity,
  secure: false,
  basic_auth: {
    user: "username",
    pass:"password"
  }
};
and replacing this  "this.client = xmlrpc.createClient(this.config);" with 
 if(!this.config.secure){
    this.client = xmlrpc.createClient(this.config);
  } else {
    this.client = xmlrpc.createSecureClient(this.config);
  }
